### ISSUE TITLE
Dockerfile is missing

### ISSUE THREAD

**Issue by JanLoebel** [jibidus/monitofen#43]
Hi,

I wanted to try your project, but the "docker-compose.yml" defines the context with "./" to build the okovision image, but there is not "Dockerfile" present. Is the Docker-Support still in work?

Best regards,
Jan

**Comment by jibidus** [comment]
Hi @JanLoebel ,

You're right, the `docker-cmpose.yml` is not usable, I will remove this file.
But you can try this project with `rails s` once all dependencies are installed (node, ruby... see [dev doc](https://github.com/jibidus/monitofen/blob/main/doc/dev.md)), but this requires to install a lot of stuff... I will create a `Dockerfile` to improve that.
In the meantime, here are the functionnalities provided by `Monitofen` (I will update `README.md` with these information):
- import daily measures in a database
- display measures for 1 day + 1 metric

![image](https://user-images.githubusercontent.com/7377177/140696755-edc30250-4ffe-4205-be3e-3535f68997b8.png)

Thank you for your issue, I hope this answer will help.

**Comment by jibidus** [comment]
Let me know if this does not help: https://github.com/jibidus/monitofen/blob/main/doc/infra.md#how-to-run-monitofen-with-a-docker-
